### ISSUE TITLE
CodeBlocksExporter for Windows?

### ISSUE THREAD

**Issue by georgy7** [Kode/kmake#19]
Currently I build a project with the command `node Kha/make`, and I get the VS solution. I imported the solution into Code::Blocks, and I could not build the resulting project with neither CLang nor TDM64-GCC. I assume, there is something wrong with macro & defines. It would be great if there was the ability to generate the working Code::Blocks project for Windows and _not_ for Visual Studio. Is the support of the option planned?

**Comment by RobDangerous** [comment]
Still no Code::Blocks for Windows but you can use vscode now - which I think is nicer anyway.
