### ISSUE TITLE
Feature Request: Enable passing parameters to `addProject` calls

### ISSUE THREAD

**Issue by tcdude** [Kode/kmake#28]
Please extend the `addProject` method to accept optional parameter(s) that can be used in the `kfile.js` of the added project.

This would allow the user to handle setup of a project depending on whether arguments were passed or not.

In my specific use case it would serve to avoid adding the same project multiple times due to nested dependencies when the project is being used as a sub-project, compared to when it is used as standalone project.

**Comment by RobDangerous** [comment]
Oh, that already exists. addProject('whereever', {a: 1, b: 2}) should get you Options.a and Options.b in the subproject.
