### ISSUE TITLE
Feature Request: Provide way to access relative path to main `DebugDir`

### ISSUE THREAD

**Issue by tcdude** [Kode/kmake#29]
Currently there appears to be no way to determine the path to the directory specified in `setDebugDir` of the top most project, thus no straight forward way to place assets from a sub-project in that directory.

A way to determine that directory inside the kfile of a sub-project for copy operations would be great.

**Comment by RobDangerous** [comment]
get/setDebugDir now sets a static var - that means you can get it from the project-var in the sub-project via getDebugDir. Also means calling setDebugDir will overwrite it for all parent-projects and all sub-projects - which I think makes sense because there can really only be one anyway.
