### ISSUE TITLE
[Feature Request] option to only output JSON information to stdout

### ISSUE THREAD

**Issue by samhocevar** [Kode/kmake#34]
I would like to use `kmake` a bit like `pkg-config`, *i.e.* retrieve `CFLAGS`, `LDFLAGS` etc. for use in my build system. The `--json` flag almost gets me there, except for:
 - it outputs to a file; support for `/dev/stdout` would be nice (if only to avoid race conditions with parallel builds)
 - it re-creates all the build files; this undoes my post-kmake steps so I need to be extra careful with the order of operations

None of that is really critical and I can find workarounds, but it would be nice to have. Does that make sense?

**Comment by RobDangerous** [comment]
In my tests it only recreated the shaders, disabled that now. And you can now add --stdout.
