### ISSUE TITLE
Feature request: Add a way to specify target GLSL version in a kfile

### ISSUE THREAD

**Issue by tcdude** [Kode/kmake#52]
Please add a way to specify/override the target GLSL version for a project in the kfile.js

**Comment by sh-dave** [comment]
Like that one?

https://github.com/Kode/kmake/blob/c5aa45170e551e02562065cda6495f43768bcad2/kmake/src/Project.ts#L869-L871

**Comment by tcdude** [comment]
Exactly like that one 😅
